# Default Kibana configuration for docker target
server.host: "0.0.0.0"
server.shutdownTimeout: "5s"
elasticsearch.hosts: [ "https://es01:9200" ]
xpack.reporting.roles.enabled: false
xpack.reporting.kibanaServer.hostname: localhost
xpack.encryptedSavedObjects.encryptionKey: 262e15dac73c1a3ae153f311bf2d0892
xpack.reporting.encryptionKey: 1c0693f7f19e5be23a534ae1f2a17fe1
xpack.security.encryptionKey: ca9b5ef4bc35f7cc53cfe8c35bb16bc8
elasticsearch.username: "kibana_system"
elasticsearch.password: Z=TzL1e+E*rbvAik9sYG
